import os
from SCons.Environment import Environment
from build_scripts.utility import GlobRecursive, FindIndex, IsFileName
from itertools import chain

Import('TARGET_ENVIRONMENT')
TARGET_ENVIRONMENT: Environment

# Clone environment
env = TARGET_ENVIRONMENT.Clone()

# Add linker flags, include paths, and assembler flags
env.Append(
    LINKFLAGS=[
        '-Wl,-T', env.File('linker.ld').srcnode().path,
        '-Wl,-Map=' + env.File('kernel.map').path
    ],
    CPPPATH=[
        env.Dir('.').srcnode(),
        env['PROJECTDIR'].Dir('src/libs')
    ],
    ASFLAGS=[
        '-I', env.Dir('.').srcnode(),
    ]
)

sources = GlobRecursive(env, '*.c') + \
          GlobRecursive(env, '*.cpp') + \
          GlobRecursive(env, '*.asm')

# FILTER OUT old Jetson files that conflict with the new interactive version
old_jetson_files = [
    'jetson_about.c',
    'jetson_animation.c',
    'jetson_keyboard.c',
    'jetson_terminal.c',
    'jetson_file_browser.c',
    'jetson_system_info.c',
    'jetson_desktop.c',
    'jetson_vga_wrapper.c',
    'jetson_utils.c',
]

# Filter sources to exclude old files
filtered_sources = []
for source in sources:
    source_name = str(source).split('/')[-1]
    if source_name not in old_jetson_files:
        filtered_sources.append(source)

objects = env.Object(filtered_sources)

# Reorder crt objects
obj_crti = objects.pop(FindIndex(objects, lambda item: IsFileName(item, 'crti.o')))
obj_crtn = objects.pop(FindIndex(objects, lambda item: IsFileName(item, 'crtn.o')))

# Link against static libraries
Import('libcore')
static_libs = [
    libcore,
]

# Final object list for linking
objects = [
    obj_crti,
    os.path.join(env["TOOLCHAIN_LIBGCC"], 'crtbegin.o'),
    *objects,
    *static_libs,
    os.path.join(env["TOOLCHAIN_LIBGCC"], 'crtend.o'),
    obj_crtn
]

# Link kernel ELF
kernel = env.Program('kernel.elf', objects)

# Export for higher-level scripts
Export('kernel')